config/routes.rb
Rails.application.routes.draw do

    mount Shoppe::Engine => '/admin'
  
    get 'products' => 'products#categories', :as => 'catalogue'
    get 'products/filter' => 'products#filter', :as => 'product_filter'
    get 'products/:category_id' => 'products#index', :as => 'products'
    get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
    post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
    

    #
    # Order status
    #
    get 'order/:token' => 'orders#status', :as => 'order_status'

    #
    # Basket
    #
    get 'basket' => 'orders#show', :as => 'basket'
    delete 'basket' => 'orders#destroy', :as => 'empty_basket'
    post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
    delete 'basket/:order_item_id' => 'orders#change_item_quantity'
    delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
    #
    # Checkout
    #
    match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
    match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
    match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch, :post]
    match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
    #
    # Static pages
    #
    #get ':action', :controller => 'pages', :as => 'page'
  
    # 
    # Homepage
    #
    root :to => 'pages#home'
end

app/views/shared/_app_icons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_url 'app_icons/apple-icon-57x57.png'%>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_url 'app_icons/apple-icon-60x60.png'%>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_url 'app_icons/apple-icon-72x72.png'%>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_url 'app_icons/apple-icon-76x76.png'%>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_url 'app_icons/apple-icon-114x114.png'%>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_url 'app_icons/apple-icon-120x120.png'%>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_url 'app_icons/apple-icon-144x144.png'%>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_url 'app_icons/apple-icon-152x152.png'%>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_url 'app_icons/apple-icon-180x180.png'%>">
<link rel="icon" type="image/png" sizes="192x192"  href="<%= image_url 'app_icons/android-icon-192x192.png'%>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_url 'app_icons/favicon-32x32.png'%>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_url 'app_icons/favicon-96x96.png'%>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_url 'app_icons/favicon-16x16.png'%>">
<link rel="manifest" href="<%= image_url 'app_icons/manifest.json'%>">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<%= image_url 'app_icons/ms-icon-144x144.png'%>">
<meta name="theme-color" content="#ffffff">

app/views/shared/_banner.html.erb
<div class="banner" id="slider">
  <div class="container">
    <div class="header_top">
      <div class="header_top_left">
        <div class="box_11">
          <%= render 'layouts/shared/basket' %>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="header_bottom">
      <div class="logo">
        <%= image_tag('by_frida_em_logo.jpeg') %>
      </div>
      <div class="menu">
        <ul class="megamenu skyblue">
          <li>
            <%= link_to 'Hem', root_path, class: 'color2' %>
          </li>
          <li>
            <%= link_to 'Om oss', page_path(:why), class: 'color2' %>
          </li>
          <li>
            <%= link_to 'Produkter', '#', class: 'color2' %>
            <div class="megapanel">
              <div class="row">
                <div class="col2">
                  <div class="h_nav">
                    <ul>
                      <% for category in procuct_categories %>
                        <li>
                          <%= link_to category.name.upcase, products_path(category.permalink), class: 'color2' %>
                        </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <%= link_to 'Frågor & Svar', page_path(:faqs), class: 'color2' %>
          </li>
          <li>
            <%= link_to_unless_current 'Kontakta oss', page_path(:contact), class: 'color2' %>
          </li>
        </ul>


      </div>
      <div class="clearfix"></div>
      <div class="logo">
        <h1><span class="m_1">A</span>n inner tube from <span class="m_1">M</span>almö lost its function</h1>
        <h2>by Frida <span class="m_1">EM</span> gave it a new purpose</h2>
        <h1>to <span class="m_1">EM</span>brace and <span class="m_1">EM</span>power you.</h1>
      </div>

    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    $("#slider").vegas({
      transition: 'fade',
      overlay: '<%= image_path 'overlays/08.png' %>',
      transitionDuration: 2000,
      slides: [
        {src: "<%= image_path 'slider/bfem_1.jpg' %>"},
        {src: "<%= image_path 'slider/bfem_2.jpg' %>"},
        {src: "<%= image_path 'slider/bfem_3.jpg' %>"},
        {src: "<%= image_path 'slider/bfem_4.jpg' %>"},
        {src: "<%= image_path 'slider/bfem_5.jpg' %>"},
        {src: "<%= image_path 'slider/bfem_6.jpg' %>"},
        {src: "<%= image_path 'slider/bfem_7.jpg' %>"},
        {src: "<%= image_path 'slider/bfem_8.jpg' %>"},
        {src: "<%= image_path 'slider/bfem_9.jpg' %>"}
      ]
    });
  });

</script>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="cssmenu">
        <ul>
          <li class="active"><%= link_to 'Hem', root_path, class: 'color2' %></li>
          <li><%= link_to 'Om oss', page_path(:why), class: 'color2' %></li>
          <li><%= link_to 'Frågor & Svar', page_path(:faqs), class: 'color2' %></li>
          <li><%= link_to 'Kontakta oss', page_path(:contact), class: 'color2' %></li>
        </ul>
      </div>
      <ul class="social">
        <li><a href="https://www.instagram.com/byfridaem/" target="_blank"> <i class="instagram"> </i> </a></li>
        <li><a href="https://www.facebook.com/Byfridaem" target="_blank"><i class="fb"> </i> </a></li>
        <li><a href="https://twitter.com/hashtag/byfridaem"><i class="tw"> </i> </a></li>
      </ul>
      <div class="clearfix"></div>
      <div class="copy">
        <p>Innehåll och bilder &copy; <%= Date.today.year %> ByFridaEM.</p>
        <p>Running on <%= image_tag 'social/ruby.svg', style: 'height: 11px; width: 11px;' %> on Rails
          Coded with <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
          by <%= link_to 'CraftAcademy', 'http://www.craftacademy.se' %>.
        </p>
      </div>
    </div>
  </div>

</div>

app/views/shared/_image.html.erb
<div class="zoom">
  <div class="zoom__top zoom__left"></div>
  <div class="zoom__top zoom__centre"></div>
  <div class="zoom__top zoom__right"></div>
  <div class="zoom__middle zoom__left"></div>
  <div class="zoom__middle zoom__centre"></div>
  <div class="zoom__middle zoom__right"></div>
  <div class="zoom__bottom zoom__left"></div>
  <div class="zoom__bottom zoom__centre"></div>
  <div class="zoom__bottom zoom__right"></div>
  <img class="zoom__image" src="<%= product.default_image.path %>" alt="">
</div>

app/views/shared/_meta_tags.html.erb
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="<%= "#{shared_meta_keywords}#{ content_for?(:keywords) ? ",#{yield(:keywords)}" : ''}" %>">
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">
<meta name="author" content="<%= content_for?(:author) ? yield(:author) : 'ByFridaEM' %>">
<% if content_for?(:robots) %>
    <meta name="robots" content="<%= yield(:robots) %>">
<% end %>
<meta name="copyright" content="ByFridaEM">
<meta name="coverage" content="Worldwide">
<meta name="distribution" content="Global">
<meta name="application-name" content="ByFridaEM e-commerce site">

<meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : 'ByFridaEM' %>"/>
<meta property="og:type" content="<%= params[:controller] == 'products' ? 'product' : 'website' %>"/>
<meta property="og:url" content="<%= request.original_url %>"/>
<meta property="og:site_name" content="ByFridaEM"/>
<meta property="og:description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">
<meta property="og:image" content="<%= asset_path 'screenshot.png' %>">

<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="<%= content_for?(:title) ? yield(:title) : 'ByFridaEM' %>"/>
<meta name="twitter:url" content="<%= request.original_url %>">
<meta name="twitter:site" content="@LashQueen">
<meta name="twitter:image:src" content="<%= asset_path 'screenshot.png' %>">
<% if content_for?(:twitter_creator) %>
    <meta name="twitter:creator" content="<%= yield(:twitter_creator) %>">
<% end %>
<meta name="twitter:description" content="<%= content_for?(:description) ? yield(:description) : default_meta_description %>">

app/views/shared/_order_items.html.haml
%table.orderItems
  %thead
    %tr
      %td Antal
      %td Vara
      %td Pris
      %td= Shoppe.settings.tax_name
      %td Totalt
  %tbody
    - for item in order.order_items
      %tr
        %td.quantity
          - unless defined?(readonly)
            %span
              = link_to '+', adjust_basket_item_quantity_path(item.id), method: :post, class: 'ajax'
              = link_to '-', adjust_basket_item_quantity_path(item.id), method: :delete, class: 'ajax'
          = item.quantity
        %td.product
          = item.ordered_item.full_name
          - unless defined?(readonly)
            = link_to 'Ta bort', remove_basket_item_path(item), method: :delete, class: 'delete ajax'
        %td.money.price= number_to_currency item.sub_total, format: '%n %u'
        %td.money.tax= number_to_currency item.tax_amount, format: '%n %u'
        %td.money.total= number_to_currency item.total, format: '%n %u'
  %tfoot
    - if order.delivery_service
      %tr.delivery
        %td.method{colspan: 4}
          - if defined?(readonly)
            = order.delivery_service.name
          - else
            = form_tag change_delivery_service_path do
              = select_tag 'delivery_service', options_from_collection_for_select(order.available_delivery_services, :id, :name, order.delivery_service.id)
        %td.money= number_to_currency order.delivery_price, format: '%n %u'
    %tr.subtotal
      %td{:colspan => 4} Total (exklusive #{Shoppe.settings.tax_name})
      %td.money= number_to_currency order.total_before_tax, format: '%n %u'
    %tr.tax
      %td{:colspan => 4}= Shoppe.settings.tax_name
      %td.money= number_to_currency order.tax, format: '%n %u'
    %tr.total
      %td{:colspan => 4} Total
      %td.money= number_to_currency order.total, format: '%n %u'

app/views/shared/_product_list.html.erb
<!-- card list -->
<ul class="flex-card-list">
  <!-- card list item -->
  <% for product in products.includes(:default_image, :product_categories) %>
    <li class="flex-card-listitem">
      <!-- card module -->
      <div class="flex-card">
        <!-- image container -->
        <div class="flex-card-image">
          <%= render 'shared/image', product: product %>
        </div>
        <!-- content container -->
        <div class="flex-card-content">
          <h3 class="flex-card-heading"><%= link_to product.name, product_path(product.product_category.permalink, product.permalink) %></h3>

          <p><%= truncate product.short_description, length: 90 %></p>

          <%= link_to 'Info', product_path(product.product_category.permalink, product.permalink), class: 'flex-card-button' %>
          <% if product.orderable? %>
            <%= link_to 'Lägg till', buy_product_path(product.product_category.permalink, product.permalink), class: 'flex-card-button', method: :post %>
          <% end %>
          </p>
          <% unless product.has_variants? %>
            <p >
              <%= "#{number_to_currency product.price_including_tax, format: '%n %u' }" %>
            </p>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>
      

app/views/shared/_products.html.erb
<div class="content_middle_bottom" style="margin-top: 50px;">
  <div class="header-left" id="home">
    <section>
      <ul class="lb-album">
        <!-- card list item -->
        <% for product in products.includes(:default_image, :product_categories) %>
          <li>


            <a href="<%= product_path(product.product_category.permalink, product.permalink) %>">
              <%= render 'shared/image', product: product %>
              <span><%= product.name %></span><br/>
            </a>

            <div class="lb-overlay" id="image-<%= product.default_image.id %>">
              <a href="#page" class="lb-close">Close</a>
              <%= link_to 'Info', product_path(product.product_category.permalink, product.permalink), class: 'lb-close btn btn-primary' %>
              <% if product.orderable? %>
                <%= link_to 'Lägg till', buy_product_path(product.product_category.permalink, product.permalink), class: 'lb-close btn btn-primary', method: :post %>
              <% end %>
              <img src="<%= product.default_image.path %>" class="img-responsive" alt="image<%= product.default_image.id %>"/>

              <div>
                <h3><%= link_to product.name, product_path(product.product_category.permalink, product.permalink) %></h3>

                <p><%= truncate product.short_description, length: 90 %></p>

                </p>
                <% unless product.has_variants? %>
                  <p>
                    <%= "#{number_to_currency product.price_including_tax, format: '%n %u' }" %>
                  </p>
                <% end %>
              </div>
              <div>

              </div>
            </div>
          </li>
        <% end %>
        <div class="clearfix"></div>
      </ul>
    </section>
  </div>
</div>

app/views/shared/_reasons.html.haml
%ul.reasons
  %li.quality
    %h4 Kvalitet och omtanke
    %p Alla våra produkter tillverkas för hand av återvunnen material.
  %li.delivery
    %h4 Snabb leverans
    %p Beställ innan kl 15.00 skickar vi varorna redan samma dag.
  %li.support
    %h4 Kunnig support
    %p Vi finns här för att hjälpa dig och delar gärma med oss av våra erfarenheter.