config/routes.rb
Rails.application.routes.draw do

    mount Shoppe::Engine => '/admin'
  
    get 'products' => 'products#categories', :as => 'catalogue'
    get 'products/filter' => 'products#filter', :as => 'product_filter'
    get 'products/:category_id' => 'products#index', :as => 'products'
    get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
    post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
    

    #
    # Order status
    #
    get 'order/:token' => 'orders#status', :as => 'order_status'

    #
    # Basket
    #
    get 'basket' => 'orders#show', :as => 'basket'
    delete 'basket' => 'orders#destroy', :as => 'empty_basket'
    post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
    delete 'basket/:order_item_id' => 'orders#change_item_quantity'
    delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
    #
    # Checkout
    #
    match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
    match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
    match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch, :post]
    match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]
  
    #
    # Static pages
    #
    #get ':action', :controller => 'pages', :as => 'page'
  
    # 
    # Homepage
    #
    root :to => 'pages#home'
end

app/views/pages/contact.html.haml
- active_nav_item :contact
- @page_title = 'Kontakta oss'
.content
  %h2 Kontakt
  %p Tveka inte att kontakta oss...

app/views/pages/contact.mobile.erb
<%= render 'layouts/shared/mobile/basket_pop' %>

<h1>Kontakta oss...</h1>

app/views/pages/faqs.html.haml
- active_nav_item :faqs
- @page_title = 'Frågor & Svar'
.content
  %h2 Svar på vanligt förekommande frågor
  %h3 Rubrik
  %p Text

app/views/pages/home.html.haml
- active_nav_item :home
- @full_header = true
- @page_title = 'Välkommen'

.home
  %p.browse= link_to 'Bläddra i vår katalog', catalogue_path
  %h2 Populära produkter

= render 'shared/products', :products => @products.includes(:default_image)

app/views/pages/home.mobile.erb
<% active_nav_item :home %>
<% @full_header = true %>
<% @page_title = 'Välkommen' %>
<%#= render 'layouts/shared/mobile/basket_pop' %>

<%#= link_to 'Bläddra i vår katalog', catalogue_path %>
<!--h2>Utvalda produkter</h2>
<br/-->
<%#= render 'shared/mobile/product_list', :products => @products.includes(:default_image) %>
<h1>Mobilversionen är under uppbyggnad.</h1>
<p>Besök oss gärna på en stationär eller bärbar dator.</p>

app/views/pages/privacy.html.haml
- @page_title = 'Personlig information'
.content
  %h2 Hur behandlar vi din personliga information?
  %p När du handlar från en webbutik lämnar du ifrån dig information om dig själv. Var du bor, vilken e-postadress du har och vad du handlar. Vissa av våra kunder undrar vad vi gör med informationen och här beskriver vi lite mer formellt hur vi arbetar med information.
  %p Grunden i allt vi gör är att behandla våra kunder som vi själva vill bli behandlade, alltid. Det gäller även när det kommer till information.

  %h2 Vilken information samlar vi in?
  %p Vi samlar in så lite information som möjligt. Vi behöver veta var du bor för att kunna skicka varorna hem till dig. Beställer du till ditt jobb eller sommarställe behöver vi inte ens veta var du bor.

  //%p Vill du beställa mot faktura så måste vår sammarbetspartner Klarna ha ditt personnummer. Bara då kan du få dina varor hemskickade mot faktura.

  %p När du betalar med kort så krävs det att du uppger ditt kreditkortsnummer. Det går via en säker server och Klarna eller DIBS sköter kortbetalningar via oss.

  %p Vi måste såklart även veta vilka produkter du beställer och vi behöver din e-postadress för att kunna kontakta dig med leveransbesked, ändrad information osv.

  %h2 Hur använder vi den här informationen?
  %p Vi använder informationen för att expediera din beställning. Vi använder din e-postadress för att kunna skicka information till dig. Vill du inte ha information från oss så kan du enkelt via en länk informationsmailet avbeställa vidare informationsbrev och kommer då aldrig bli kontaktad av oss igen.

  %h2 Cookies
  %p Vi använder cookies - det gör vi för att kunna lagra dina varor i din varukorg.

  %p Vi använder dessutom Googles tjänster "Google Analytics" och annan tredjepart mjukvara. Även dessa tjänster använder Cookies.

  %h2 Information till andra aktörer
  %p Vi lämnar aldrig ifrån oss din information till någon annan. Undantag görs om vi av någon anledning är tvingade enligt lag.

  %h2 Ta bort din information från vår databas
  %p Den enda informationen som vi behåller är din e-postadress. Resterande information sparas bara som underlag för den ekonomiska transaktionen.

  %p Vill du inte att vi har din e-postadress i vår databas för informationsbrev så kan du maila oss så tar vi bort den.

app/views/pages/returns.html.haml
- @page_title = 'Returer och byten'
.content
  %h2 Returer och byten
  %p Tack för att du har valt att handla hos oss. Vi hoppas att du blir nöjd med din beställning. Om du inte skulle vara helt nöjd, har du möjlighet att returnera eller byta dina stödstrumpor eller fotvårdsprodukter.
  %h3 Ångerrätt – om du ångrar ditt köp
  %p Full ångerrätt gäller 14 dagar från det att du mottagit ditt köp. Vid en retur skall varan vara i oanvänt skick och returneras i originalförpackningen. Med oanvänt skick menas att varan, efter provning, är hel och ren och i säljbart nyskick. Undantaget är underkläder (trosor och boxer) som inte får provas, och de ska returneras i obruten förpackning. Skicka alltid varan tillsammans med kvitto, faktura eller orderbekräftelse och ange orsak till retur.
  %p Vid godkänd retur återbetalar vi summan för returen eller hela ordersumman. Har kunden betalat via sin internetbank behöver vi kontonummer för att kunna återbetala ordern. I alla andra fall återbetalar vi automatiskt tillbaka till det kontot som användes i samband med köpet. Kunden står för returporto.
  %h3 Byten
  %p Vi erbjuder 30 dagars bytesrätt på varor i oanvänt skick. Bytesrätten gäller vid t.ex byte av storlek eller färg. Maila kundtjänst på info@butik21.com eller ring 08-27 88 50 för att få hjälp med att hitta rätt produkt för dig. Kunden står för returporto.
  %h3 Reklamation
  %p Reklamationen gäller på varor inom 30 dagar från genomfört köp. Reklamation gäller t.ex. vid fabrikationsfel, som till exempel trasiga sömmar. Reklamationsrätten innefattar inte förslitningsskador. Maila vår kundtjänst vid reklamationer innan ni skickar tillbaka returen.
  %p Vid godkänd reklamation återbetalar vi summan för returen eller hela ordersumman samt står för returportot.
  %h3 Ogiltiga returer
  %p Är du osäker på om du har rätt till byte eller retur, var god kontakta vår kundtjänst. Ogiltiga returer kommer skickas tillbaka till kund mot ett förskott på portokostnaden.
  %h3 Kostnad för ej uthämtad paket
  %p  Om du ångrar dig innan du får ditt paket bör du ändå hämta ut ditt paket och sedan skicka tillbaka det till oss. Vi tar ut en administrativ avgift på 250 kr för ej uthämtade paket. Anledningen är att det kostar oss väldigt mycket och tar väldigt lång tid att få tillbaka paket som inte hämtas ut.

app/views/pages/terms.html.haml
- @page_title = 'Terms & Conditions'
.content
  %p Nedan följer villkor som gäller när du handlar genom webbshoppen
  %h2 Allmänna villkor
  %h4 1. Köp
  %small Vid beställning träffas avtal om köp först när ByFridaEM bekräftat beställningen genom en orderbekräftelse. En orderbekräftelse skickas senast 24 timmar efter att beställning mottagits av butik21.com. Om leveranstid ändras i beställningen kommer kunden att meddelas om detta snarast möjligt. Du har alltid rätt att häva köpet utan kostnad fram till att varan är skickad. ByFridaEM har ägande och återtaganderätt till samtliga produkter tills dess att fullständig betalning har mottagits från kund. För att handla hos oss måste du vara 18 år och butik21.com måste kunna fastställa kundens bostadsadress.
  %h4 2. Priser
  %small I priserna ingår moms med 25 % för beställningar inom EU. Vid bekräftad beställning, kan priserna endast ändras av omständigheter som ByFridaEM inte råder över. Till exempel väsentligt ändrade råvarupriser, valutaförändringar eller ändrad moms. Inga expeditionskostnader tillkommer. Skulle priset ändras har kunden rätt att utan kostnad häva köpet.
  %h4 3. Frakt
  %small En fraktkostnad om 29 kr tillkommer inom Sverige.
  %h4 4. Betalningsalternativ/betalningsvillkor
  %h5 4.1 Faktura (endast inom Sverige)
  %small Avgiften för att betala mot faktura är 0 kronor. Vi använder Klarna för faktura och du hittar deras villkor här: http://www.klarna.com/sv/privat.
  %small Betalningsvillkor: Vid fakturabetalning gäller 14 dagar från det att varan skickats.  Det är Klarnas betalningsvillkor som gäller och du hittar dem här: Klarna faktura
  %h5 4.2 Kortbetalning
  %small Vi använder DIBS och Klarna för säkra kortbetalningar. Läs mer om DIBS här: http://www.dibs.se/
  %small Läs mer om Klarna här: http://www.klarna.com/sv/privat.
  %h5 4.3 Direktbetalning via internetbank.
  %small Betalning via banken sker genom Klarna. Läs mer om Klarna här: http://www.klarna.com/sv/privat
  %h5 4.4 Paypal
  %small Du har möjlighet att betala via Paypal. För mera information besök www.paypal.se.
  %h4 5. Leveranser
  %small Beställningar som görs före klockan 16.00 på helgfri vardag behandlas samma dag och levereras normalt inom 1-2 dagar inom Sverige.
  %small Vi reserverar oss för att samtliga lagervaror blir slutsålda innan vi hinner uppdatera hemsidan, och då upplyser vi kunderna om den beräknade leveranstiden. Kunden har alltid rätt att häva köp utan kostnad om inte varan finns i lager. Paketen levereras av Posten eller annan transportör till utlämningsställe eller skickas som post.
  %h4 6. Leveransförseningar
  %small Ibland uppstår leveransförseningar från våra leverantörer utom vår kontroll. Det kan till exempel ske då en leverantör inte kan fullfölja sina leveransförpliktelser mot oss eller problem i tillverkningsprocessen. Om det inträffar frånsäger vi oss ersättningsansvar till kunden för den skada som förseningen åstadkommit. Du kan lita på att vi alltid meddelar dig om leveranser drar ut på tiden. Du har som kund alltid rätt att häva köpet utan kostnad vid leveransförsening.
  %h4 7. Transport
  %small ByFridaEM ansvarar för transport till dig som kund. Du och transportföretaget står för risken vid eventuell retur till oss.
  %h4 8. Skadade varor
  %small När du får dina varor är det viktigt att du kontrollerar din beställning direkt.  Har du mottagit en felaktig eller skadad vara, kontakta oss så snart som möjligt via e-post till info@butik21.com.
  %h4 9. Ångerrätt och öppet köp
  %small Privatkunder har enligt distansavtalslagen rätt till 14 dagars ångerrätt. Detta innebär att du som kund har rätt att ångra ditt köp inom 14 dagar efter det att du har tagit emot varan. Återsänd vara måste vara oanvänd och i sin originalförpackning. Vid utnyttjande av ångerrätt/öppet köp står kunden för returfrakten.
  %small Som kund hos oss erbjuder Butik21 även bytesrätt inom 30 dagar från det att du beställt varan. Detta gäller endast oanvända produkter.
  %h4 10. Reklamationer
  %small Om du vill reklamera en skadad eller felaktig produkt ber vi dig kontakta oss via e-post för vidare instruktioner. Meddela oss helst via e-post info@butik21.com innan du skickar något. Lägg med fakturan/kvittot så vi kan identifiera returen. Kom ihåg att du ansvarar för frakten till oss.
  %small Vid en eventuell tvist följer vi alltid ARN:s rekommendationer.
  %h4 11. Återbetalningar
  %small Återbetalning sker via Klarna, PayPal eller DIBS. Summan återbetalas alltid till samma konto som använts vid köpet och snarast möjligt från det att vi har mottagit och godkänt returen.
  %h4 12. Reservationer
  %small Vi reserverar oss för ändringar i priser till följd av stora prisavvikelser från våra leverantörer, felskrivningar eller andra fel som ligger utanför vår kontroll. Läs mer om oförutsedda händelser under Force Majeur nedan.
  %h4 13. Skydd av personuppgifter
  %small I samband med registrering och beställning godkänner du att vi lagrar och använder dina uppgifter i vår verksamhet endast i syfte för att fullfölja och tillhandahålla den service som du förväntar dig av oss. Enligt PUL (personuppgiftslagen) har du rätt att få den information som vi har registrerat på dig och om du anser den vara felaktig eller irrelevant kan du begära rättelse eller borttagning ur vårt kundregister. Kontakta i så fall vår kundservice (gärna på e-post info@butik21.com). Vi försäkrar även att vi inte kommer sälja eller överlåta några personuppgifter (se vår privacy policy).
  %h4 14. Ej uthämtat paket
  %small Om ditt paket anländer till ett utlämningsställe skickas en avisering via e-post eller sms till dig. Du som kund är ansvarig för att det mobilnummer, den adress och den e-postadress du angivit är korrekta.
  %small Om du inte hämtar ut ditt paket så debiteras du en administrativ avgift på 250 kr.
  %h4 15. Force Majeur
  %small I händelse av krig, naturkatastrof, stridsåtgärder på arbetsmarknaden, myndighetsbeslut och jämförbara händelser utanför vår kontroll vilka ej skäligen kunnat förutses, och påverkar ingångna avtal samt utfästelser från vår sida, som gör att vi ej kan hålla nämnda avtal/utfästelse, skall utgöra grund till att vi befrias från våra förpliktelser att fullgöra nämnda avtal.
  %p Nedan följer länkar till Konsumentverket och ARN där du kan läsa mer detaljerat om konsumentköplagen och distansavtalslagen mm.
  %p http://www.konsumentverket.se/ http://www.arn.se/

app/views/pages/why.html.haml
- active_nav_item :why
- @page_title = 'Om oss'
.content
  %h2 by Frida EM
  %p
    By Frida EM Elegance, strength & passion in perfect symbiosis. Sustainable & modular handmade luxury from Malmö,Sweden. Business inquiries;byfridaem@gmail.com